language: node_js
cache: yarn
node_js:
  - "10.16.0"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn global add gulp-cli
  - yarn install
script:
  - yarn run init
  - yarn run build-prod