language: node_js
cache: yarn
services:
  - docker
node_js:
  - "10.16.0"
env:
  global:
  - DOCKER_REPO=buildly/buildly-ui
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn global add gulp-cli
  - yarn install
script:
  - yarn run init
  - yarn run build-prod
  - docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker tag $DOCKER_REPO "$DOCKER_REPO:$TRAVIS_TAG" && docker push "$DOCKER_REPO:$TRAVIS_TAG"
  on:
    branch: master
    tags: true
